#!/usr/bin/env python3
"""
CachaTuMusica
=============

Este script recorre directorios buscando archivos de audio y actualiza
sus metadatos ID3 utilizando audio fingerprinting (AcoustID/MusicBrainz)
y como fallback, APIs de IA.

Requisitos:
    - Python 3.8+
    - API Key de AcoustID (https://acoustid.org/)
    - API Key de OpenAI u otro proveedor LLM (opcional)

Uso:
    python audio_tagger.py --dir /ruta/a/musica --backup

Autor: Generated by OpenCode
"""

import os
import sys
import csv
import json
import shutil
import argparse
import hashlib
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, List, Tuple, Any
from dataclasses import dataclass, asdict
from concurrent.futures import ThreadPoolExecutor, as_completed

# Procesamiento de audio
import mutagen
from mutagen import File
from mutagen.mp3 import MP3
from mutagen.flac import FLAC
from mutagen.wavpack import WavPack
from mutagen.easyid3 import EasyID3
from mutagen.id3 import ID3, TIT1, TIT2, TPE1, TALB, TDRC, TCON

# Barra de progreso
from tqdm import tqdm

# Fingerprinting
import acoustid
import musicbrainzngs

# Logging
import logging

# Configuración de logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Géneros estandarizados
GENEROS_ESTANDARIZADOS = {
    'rock': 'Rock',
    'classic rock': 'Rock',
    'alt rock': 'Rock',
    'alternative rock': 'Rock',
    'hard rock': 'Rock',
    'pop': 'Pop',
    'synth-pop': 'Pop',
    'electropop': 'Pop',
    'dance-pop': 'Pop',
    'electronic': 'Electronic',
    'edm': 'Electronic',
    'house': 'Electronic',
    'techno': 'Electronic',
    'trance': 'Electronic',
    'dubstep': 'Electronic',
    'ambient': 'Electronic',
    'jazz': 'Jazz',
    'smooth jazz': 'Jazz',
    'bebop': 'Jazz',
    'classical': 'Classical',
    'baroque': 'Classical',
    'romantic': 'Classical',
    'opera': 'Classical',
    'symphony': 'Classical',
    'hip hop': 'Hip-Hop',
    'rap': 'Hip-Hop',
    'trap': 'Hip-Hop',
    'r&b': 'R&B',
    'rnb': 'R&B',
    'soul': 'R&B',
    'funk': 'R&B',
    'blues': 'Blues',
    'country': 'Country',
    'folk': 'Folk',
    'acoustic': 'Folk',
    'reggae': 'Reggae',
    'metal': 'Metal',
    'heavy metal': 'Metal',
    'death metal': 'Metal',
    'black metal': 'Metal',
    'latin': 'Latin',
    'salsa': 'Latin',
    'bachata': 'Latin',
    'reggaeton': 'Latin',
    'cumbia': 'Latin',
    'indie': 'Indie',
    'indie rock': 'Indie',
    'indie pop': 'Indie',
    'alternative': 'Alternative',
    'punk': 'Punk',
    'punk rock': 'Punk',
    'ska': 'Ska',
    'world': 'World',
    'soundtrack': 'Soundtrack',
    'ost': 'Soundtrack',
}


@dataclass
class AudioTags:
    """Estructura para almacenar metadatos de audio"""
    title: Optional[str] = None
    artist: Optional[str] = None
    album: Optional[str] = None
    year: Optional[str] = None
    genre: Optional[str] = None
    track: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'AudioTags':
        return cls(**data)


@dataclass
class ResultadoActualizacion:
    """Estructura para reporte de resultados"""
    archivo: str
    estado: str  # 'Actualizado', 'No encontrado', 'Error'
    datos_previos: AudioTags
    datos_nuevos: AudioTags
    fuente: str  # 'MusicBrainz', 'IA', 'N/A'
    mensaje: str = ""


class Configuracion:
    """Gestión de configuración y API keys"""
    
    def __init__(self, config_file: str = "config.json"):
        self.config_file = config_file
        self.acoustid_api_key: str = ""
        self.musicbrainz_user: str = ""
        self.musicbrainz_password: str = ""
        self.openai_api_key: str = ""
        self.ia_enabled: bool = False
        self.cargar_configuracion()
    
    def cargar_configuracion(self):
        """Carga configuración desde archivo JSON o variables de entorno"""
        # Primero intentar desde archivo
        if os.path.exists(self.config_file):
            try:
                with open(self.config_file, 'r', encoding='utf-8') as f:
                    config = json.load(f)
                    self.acoustid_api_key = config.get('acoustid_api_key', '')
                    self.musicbrainz_user = config.get('musicbrainz_user', '')
                    self.musicbrainz_password = config.get('musicbrainz_password', '')
                    self.openai_api_key = config.get('openai_api_key', '')
                    self.ia_enabled = config.get('ia_enabled', False)
            except Exception as e:
                logger.warning(f"No se pudo cargar config.json: {e}")
        
        # Variables de entorno tienen prioridad
        self.acoustid_api_key = os.getenv('ACOUSTID_API_KEY', self.acoustid_api_key)
        self.musicbrainz_user = os.getenv('MUSICBRAINZ_USER', self.musicbrainz_user)
        self.musicbrainz_password = os.getenv('MUSICBRAINZ_PASSWORD', self.musicbrainz_password)
        self.openai_api_key = os.getenv('OPENAI_API_KEY', self.openai_api_key)
        self.ia_enabled = os.getenv('IA_ENABLED', str(self.ia_enabled)).lower() == 'true'
        
        # Configurar MusicBrainz
        musicbrainzngs.set_useragent(
            "CachaTuMusica",
            "1.0",
            "contact@example.com"
        )
        if self.musicbrainz_user and self.musicbrainz_password:
            musicbrainzngs.auth(self.musicbrainz_user, self.musicbrainz_password)
    
    def validar(self) -> bool:
        """Valida que las configuraciones necesarias estén presentes"""
        if not self.acoustid_api_key:
            logger.error("ACOUSTID_API_KEY es requerida. Obtén una en https://acoustid.org/")
            return False
        return True


class BackupManager:
    """Gestiona copias de seguridad de archivos de audio"""
    
    def __init__(self, directorio_raiz: str):
        self.directorio_raiz = Path(directorio_raiz)
        self.backup_dir = self.directorio_raiz / f".backup_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        self.archivos_backup: List[Path] = []
    
    def crear_backup(self, archivo: Path) -> Path:
        """Crea backup de un archivo de audio"""
        # Calcular ruta relativa para mantener estructura
        ruta_relativa = archivo.relative_to(self.directorio_raiz)
        destino = self.backup_dir / ruta_relativa
        destino.parent.mkdir(parents=True, exist_ok=True)
        
        shutil.copy2(archivo, destino)
        self.archivos_backup.append(destino)
        return destino
    
    def restaurar_backup(self):
        """Restaura todos los archivos desde el backup"""
        logger.info("Restaurando archivos desde backup...")
        for backup_file in self.archivos_backup:
            ruta_relativa = backup_file.relative_to(self.backup_dir)
            original = self.directorio_raiz / ruta_relativa
            shutil.copy2(backup_file, original)
        logger.info(f"Restaurados {len(self.archivos_backup)} archivos")


class IATagger:
    """Integración con APIs de IA para inferir metadatos"""
    
    def __init__(self, api_key: str, enabled: bool = True):
        self.api_key = api_key
        self.enabled = enabled and bool(api_key)
    
    def inferir_desde_nombre(self, nombre_archivo: str, tags_actuales: AudioTags) -> Optional[AudioTags]:
        """Usa IA para inferir metadatos desde el nombre del archivo"""
        if not self.enabled:
            return None
        
        try:
            # Implementación básica usando OpenAI
            import openai
            openai.api_key = self.api_key
            
            prompt = f"""Analiza este nombre de archivo de audio e intenta inferir los metadatos musicales.
            
Archivo: {nombre_archivo}
Metadatos actuales (pueden estar vacíos):
- Título: {tags_actuales.title or 'Desconocido'}
- Artista: {tags_actuales.artist or 'Desconocido'}
- Álbum: {tags_actuales.album or 'Desconocido'}
- Año: {tags_actuales.year or 'Desconocido'}
- Género: {tags_actuales.genre or 'Desconocido'}

Responde SOLO en formato JSON con esta estructura exacta:
{{
    "title": "nombre de la canción",
    "artist": "nombre del artista",
    "album": "nombre del álbum",
    "year": "año",
    "genre": "género",
    "confidence": "alta/media/baja"
}}

Si no puedes determinar algún campo, usa null.
"""
            
            response = openai.ChatCompletion.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "Eres un experto en metadatos musicales. Analiza nombres de archivos de audio y extrae información precisa."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3,
                max_tokens=300
            )
            
            contenido = response.choices[0].message.content.strip()
            
            # Extraer JSON de la respuesta
            if '```json' in contenido:
                contenido = contenido.split('```json')[1].split('```')[0].strip()
            elif '```' in contenido:
                contenido = contenido.split('```')[1].split('```')[0].strip()
            
            datos = json.loads(contenido)
            
            # Solo usar si la confianza es suficiente
            if datos.get('confidence') in ['alta', 'media']:
                return AudioTags(
                    title=datos.get('title'),
                    artist=datos.get('artist'),
                    album=datos.get('album'),
                    year=str(datos.get('year')) if datos.get('year') else None,
                    genre=self._estandarizar_genero(datos.get('genre'))
                )
            
            return None
            
        except Exception as e:
            logger.warning(f"Error en IA tagging: {e}")
            return None
    
    def _estandarizar_genero(self, genero: Optional[str]) -> Optional[str]:
        """Estandariza el género musical"""
        if not genero:
            return None
        
        genero_lower = genero.lower()
        return GENEROS_ESTANDARIZADOS.get(genero_lower, genero.title())


class AudioTagger:
    """Clase principal para etiquetado de audio"""
    
    FORMATOS_SOPORTADOS = {'.mp3', '.flac', '.wav', '.m4a', '.ogg', '.wma'}
    
    def __init__(self, config: Configuracion, backup: bool = True):
        self.config = config
        self.backup_manager: Optional[BackupManager] = None
        self.hacer_backup = backup
        self.ia_tagger = IATagger(config.openai_api_key, config.ia_enabled)
        self.resultados: List[ResultadoActualizacion] = []
    
    def escanear_directorio(self, directorio: str) -> List[Path]:
        """Escanea recursivamente un directorio buscando archivos de audio"""
        archivos_audio = []
        directorio_path = Path(directorio)
        
        logger.info(f"Escaneando directorio: {directorio}")
        
        for ruta in directorio_path.rglob('*'):
            if ruta.is_file() and ruta.suffix.lower() in self.FORMATOS_SOPORTADOS:
                archivos_audio.append(ruta)
        
        logger.info(f"Encontrados {len(archivos_audio)} archivos de audio")
        return archivos_audio
    
    def leer_tags_actuales(self, archivo: Path) -> AudioTags:
        """Lee los tags ID3 actuales del archivo"""
        try:
            audio = File(archivo)
            if audio is None:
                return AudioTags()
            
            # Usar EasyID3 para MP3 si está disponible
            if isinstance(audio, MP3):
                if audio.tags is None:
                    audio.add_tags()
                try:
                    easy = EasyID3(archivo)
                    return AudioTags(
                        title=easy.get('title', [None])[0],
                        artist=easy.get('artist', [None])[0],
                        album=easy.get('album', [None])[0],
                        year=easy.get('date', [None])[0],
                        genre=easy.get('genre', [None])[0],
                        track=easy.get('tracknumber', [None])[0]
                    )
                except:
                    pass
            
            # Fallback genérico
            return AudioTags(
                title=str(audio.get('TIT2', '')),
                artist=str(audio.get('TPE1', '')),
                album=str(audio.get('TALB', '')),
                year=str(audio.get('TDRC', '')),
                genre=str(audio.get('TCON', ''))
            )
            
        except Exception as e:
            logger.warning(f"Error leyendo tags de {archivo}: {e}")
            return AudioTags()
    
    def identificar_con_fingerprint(self, archivo: Path) -> Optional[Dict[str, Any]]:
        """Identifica una canción usando audio fingerprinting"""
        try:
            # Generar fingerprint con AcoustID
            duracion, fingerprint = acoustid.fingerprint_file(str(archivo))
            
            # Buscar en AcoustID
            resultados = acoustid.lookup(
                self.config.acoustid_api_key,
                fingerprint,
                duracion,
                meta='recordings releases tracks'
            )
            
            if resultados['status'] != 'ok':
                return None
            
            results = resultados.get('results', [])
            if not results:
                return None
            
            # Tomar el mejor resultado (mayor score)
            mejor_resultado = max(results, key=lambda x: x.get('score', 0))
            
            if mejor_resultado.get('score', 0) < 0.7:  # Score mínimo de confianza
                return None
            
            # Extraer información de MusicBrainz
            recordings = mejor_resultado.get('recordings', [])
            if not recordings:
                return None
            
            recording = recordings[0]
            
            # Obtener información detallada de MusicBrainz
            recording_id = recording.get('id')
            if recording_id:
                try:
                    mb_result = musicbrainzngs.get_recording_by_id(
                        recording_id,
                        includes=['artists', 'releases', 'tags']
                    )
                    return self._procesar_mb_result(mb_result)
                except:
                    # Fallback a datos básicos de AcoustID
                    return self._procesar_acoustid_result(recording)
            
            return self._procesar_acoustid_result(recording)
            
        except Exception as e:
            logger.warning(f"Error en fingerprinting de {archivo.name}: {e}")
            return None
    
    def _procesar_mb_result(self, result: Dict) -> Dict[str, Any]:
        """Procesa resultado de MusicBrainz"""
        recording = result.get('recording', {})
        
        # Artista
        artist_credit = recording.get('artist-credit', [])
        artist = artist_credit[0].get('artist', {}).get('name') if artist_credit else None
        
        # Lanzamientos (álbumes)
        releases = recording.get('release-list', [])
        release = releases[0] if releases else {}
        
        # Géneros de tags
        tags = recording.get('tag-list', [])
        genre = None
        if tags:
            # Tomar el tag más popular
            sorted_tags = sorted(tags, key=lambda x: int(x.get('count', 0)), reverse=True)
            genre = sorted_tags[0].get('name') if sorted_tags else None
        
        return {
            'title': recording.get('title'),
            'artist': artist,
            'album': release.get('title'),
            'year': release.get('date', '')[:4] if release.get('date') else None,
            'genre': genre
        }
    
    def _procesar_acoustid_result(self, recording: Dict) -> Dict[str, Any]:
        """Procesa resultado básico de AcoustID"""
        artist = recording.get('artists', [{}])[0].get('name') if recording.get('artists') else None
        
        releases = recording.get('releases', [])
        release = releases[0] if releases else {}
        
        return {
            'title': recording.get('title'),
            'artist': artist,
            'album': release.get('title'),
            'year': None,  # AcoustID no proporciona año directamente
            'genre': None
        }
    
    def estandarizar_genero(self, genero: Optional[str]) -> Optional[str]:
        """Estandariza el género musical según lista predefinida"""
        if not genero:
            return None
        
        genero_lower = genero.lower()
        return GENEROS_ESTANDARIZADOS.get(genero_lower, genero.title())
    
    def escribir_tags(self, archivo: Path, tags: AudioTags) -> bool:
        """Escribe los tags en el archivo de audio"""
        try:
            audio = File(archivo)
            if audio is None:
                return False
            
            # MP3 con ID3
            if isinstance(audio, MP3):
                if audio.tags is None:
                    audio.add_tags()
                
                # Usar ID3 directamente para más control
                id3 = ID3(archivo)
                
                if tags.title:
                    id3['TIT2'] = TIT2(encoding=3, text=tags.title)
                if tags.artist:
                    id3['TPE1'] = TPE1(encoding=3, text=tags.artist)
                if tags.album:
                    id3['TALB'] = TALB(encoding=3, text=tags.album)
                if tags.year:
                    id3['TDRC'] = TDRC(encoding=3, text=tags.year)
                if tags.genre:
                    id3['TCON'] = TCON(encoding=3, text=tags.genre)
                
                id3.save(archivo)
            
            # FLAC
            elif isinstance(audio, FLAC):
                if tags.title:
                    audio['TITLE'] = tags.title
                if tags.artist:
                    audio['ARTIST'] = tags.artist
                if tags.album:
                    audio['ALBUM'] = tags.album
                if tags.year:
                    audio['DATE'] = tags.year
                if tags.genre:
                    audio['GENRE'] = tags.genre
                
                audio.save()
            
            # Otros formatos
            else:
                if hasattr(audio, 'tags'):
                    if tags.title:
                        audio.tags['title'] = tags.title
                    if tags.artist:
                        audio.tags['artist'] = tags.artist
                    if tags.album:
                        audio.tags['album'] = tags.album
                    if tags.year:
                        audio.tags['date'] = tags.year
                    if tags.genre:
                        audio.tags['genre'] = tags.genre
                    
                    audio.save()
            
            return True
            
        except Exception as e:
            logger.error(f"Error escribiendo tags en {archivo}: {e}")
            return False
    
    def procesar_archivo(self, archivo: Path, directorio_raiz: Path) -> ResultadoActualizacion:
        """Procesa un único archivo de audio"""
        # Leer tags actuales
        tags_previos = self.leer_tags_actuales(archivo)
        
        # Crear backup si es necesario
        if self.hacer_backup:
            if self.backup_manager is None:
                self.backup_manager = BackupManager(directorio_raiz)
            self.backup_manager.crear_backup(archivo)
        
        # Intentar identificación por fingerprinting
        datos_identificados = self.identificar_con_fingerprint(archivo)
        fuente = "MusicBrainz"
        
        # Si no se identificó, intentar con IA
        if datos_identificados is None and self.ia_tagger.enabled:
            datos_ia = self.ia_tagger.inferir_desde_nombre(archivo.name, tags_previos)
            if datos_ia:
                datos_identificados = datos_ia.to_dict()
                fuente = "IA"
        
        # Si no se pudo identificar
        if datos_identificados is None:
            return ResultadoActualizacion(
                archivo=str(archivo),
                estado="No encontrado",
                datos_previos=tags_previos,
                datos_nuevos=AudioTags(),
                fuente="N/A",
                mensaje="No se pudo identificar el archivo"
            )
        
        # Crear nuevos tags
        nuevos_tags = AudioTags(
            title=datos_identificados.get('title', tags_previos.title),
            artist=datos_identificados.get('artist', tags_previos.artist),
            album=datos_identificados.get('album', tags_previos.album),
            year=datos_identificados.get('year', tags_previos.year),
            genre=self.estandarizar_genero(datos_identificados.get('genre')) or tags_previos.genre
        )
        
        # Escribir tags
        if self.escribir_tags(archivo, nuevos_tags):
            return ResultadoActualizacion(
                archivo=str(archivo),
                estado="Actualizado",
                datos_previos=tags_previos,
                datos_nuevos=nuevos_tags,
                fuente=fuente
            )
        else:
            return ResultadoActualizacion(
                archivo=str(archivo),
                estado="Error",
                datos_previos=tags_previos,
                datos_nuevos=nuevos_tags,
                fuente=fuente,
                mensaje="Error al escribir tags"
            )
    
    def procesar_directorio(self, directorio: str, max_workers: int = 4):
        """Procesa todos los archivos de audio en un directorio"""
        directorio_path = Path(directorio)
        archivos = self.escanear_directorio(directorio)
        
        if not archivos:
            logger.info("No se encontraron archivos de audio")
            return
        
        logger.info(f"Procesando {len(archivos)} archivos...")
        
        # Procesar archivos con barra de progreso
        with tqdm(total=len(archivos), desc="Etiquetando") as pbar:
            with ThreadPoolExecutor(max_workers=max_workers) as executor:
                futures = {
                    executor.submit(self.procesar_archivo, archivo, directorio_path): archivo
                    for archivo in archivos
                }
                
                for future in as_completed(futures):
                    resultado = future.result()
                    self.resultados.append(resultado)
                    pbar.update(1)
        
        logger.info(f"Procesamiento completado. {len(self.resultados)} archivos procesados.")
    
    def generar_reporte_csv(self, archivo_salida: str = "log_actualizacion.csv"):
        """Genera reporte en formato CSV"""
        with open(archivo_salida, 'w', newline='', encoding='utf-8') as f:
            fieldnames = [
                'archivo', 'estado', 'fuente',
                'titulo_previo', 'artista_previo', 'album_previo', 'año_previo', 'genero_previo',
                'titulo_nuevo', 'artista_nuevo', 'album_nuevo', 'año_nuevo', 'genero_nuevo',
                'mensaje'
            ]
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            
            for resultado in self.resultados:
                row = {
                    'archivo': resultado.archivo,
                    'estado': resultado.estado,
                    'fuente': resultado.fuente,
                    'titulo_previo': resultado.datos_previos.title,
                    'artista_previo': resultado.datos_previos.artist,
                    'album_previo': resultado.datos_previos.album,
                    'año_previo': resultado.datos_previos.year,
                    'genero_previo': resultado.datos_previos.genre,
                    'titulo_nuevo': resultado.datos_nuevos.title,
                    'artista_nuevo': resultado.datos_nuevos.artist,
                    'album_nuevo': resultado.datos_nuevos.album,
                    'año_nuevo': resultado.datos_nuevos.year,
                    'genero_nuevo': resultado.datos_nuevos.genre,
                    'mensaje': resultado.mensaje
                }
                writer.writerow(row)
        
        logger.info(f"Reporte CSV generado: {archivo_salida}")
    
    def generar_reporte_md(self, archivo_salida: str = "reporte.md"):
        """Genera reporte en formato Markdown"""
        with open(archivo_salida, 'w', encoding='utf-8') as f:
            f.write("# Reporte de Etiquetado de Audio\n\n")
            f.write(f"**Fecha:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            f.write(f"**Total de archivos procesados:** {len(self.resultados)}\n\n")
            
            # Estadísticas
            actualizados = sum(1 for r in self.resultados if r.estado == "Actualizado")
            no_encontrados = sum(1 for r in self.resultados if r.estado == "No encontrado")
            errores = sum(1 for r in self.resultados if r.estado == "Error")
            
            f.write("## Resumen\n\n")
            f.write(f"- ✅ Actualizados: {actualizados}\n")
            f.write(f"- ❌ No encontrados: {no_encontrados}\n")
            f.write(f"- ⚠️ Errores: {errores}\n\n")
            
            # Detalles por fuente
            fuentes = {}
            for r in self.resultados:
                if r.estado == "Actualizado":
                    fuentes[r.fuente] = fuentes.get(r.fuente, 0) + 1
            
            if fuentes:
                f.write("### Fuentes de Información\n\n")
                for fuente, count in fuentes.items():
                    f.write(f"- {fuente}: {count} archivos\n")
                f.write("\n")
            
            # Detalles
            f.write("## Detalles\n\n")
            for resultado in self.resultados:
                f.write(f"### {Path(resultado.archivo).name}\n\n")
                f.write(f"- **Ruta:** `{resultado.archivo}`\n")
                f.write(f"- **Estado:** {resultado.estado}\n")
                f.write(f"- **Fuente:** {resultado.fuente}\n")
                
                if resultado.mensaje:
                    f.write(f"- **Mensaje:** {resultado.mensaje}\n")
                
                if resultado.estado == "Actualizado":
                    f.write("\n**Cambios realizados:**\n\n")
                    
                    if resultado.datos_previos.title != resultado.datos_nuevos.title:
                        f.write(f"- Título: `{resultado.datos_previos.title or 'Vacío'}` → `{resultado.datos_nuevos.title}`\n")
                    if resultado.datos_previos.artist != resultado.datos_nuevos.artist:
                        f.write(f"- Artista: `{resultado.datos_previos.artist or 'Vacío'}` → `{resultado.datos_nuevos.artist}`\n")
                    if resultado.datos_previos.album != resultado.datos_nuevos.album:
                        f.write(f"- Álbum: `{resultado.datos_previos.album or 'Vacío'}` → `{resultado.datos_nuevos.album}`\n")
                    if resultado.datos_previos.year != resultado.datos_nuevos.year:
                        f.write(f"- Año: `{resultado.datos_previos.year or 'Vacío'}` → `{resultado.datos_nuevos.year}`\n")
                    if resultado.datos_previos.genre != resultado.datos_nuevos.genre:
                        f.write(f"- Género: `{resultado.datos_previos.genre or 'Vacío'}` → `{resultado.datos_nuevos.genre}`\n")
                
                f.write("\n---\n\n")
        
        logger.info(f"Reporte Markdown generado: {archivo_salida}")


def main():
    parser = argparse.ArgumentParser(
        description="Automatizador de Etiquetado Masivo de Audio con IA y Fingerprinting",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Ejemplos:
  # Ejecutar con backup automático
  python audio_tagger.py --dir /ruta/a/musica --backup

  # Sin backup, solo reporte
  python audio_tagger.py --dir /ruta/a/musica --no-backup

  # Especificar archivo de configuración
  python audio_tagger.py --dir /ruta/a/musica --config mi_config.json

  # Solo generar reporte Markdown
  python audio_tagger.py --dir /ruta/a/musica --format md
        """
    )
    
    parser.add_argument(
        '--dir', '-d',
        required=True,
        help='Directorio raíz con archivos de audio'
    )
    
    parser.add_argument(
        '--backup', '-b',
        action='store_true',
        default=True,
        help='Crear backup antes de modificar (por defecto: True)'
    )
    
    parser.add_argument(
        '--no-backup',
        action='store_true',
        help='Deshabilitar backup automático'
    )
    
    parser.add_argument(
        '--config', '-c',
        default='config.json',
        help='Archivo de configuración JSON (por defecto: config.json)'
    )
    
    parser.add_argument(
        '--format', '-f',
        choices=['csv', 'md', 'both'],
        default='both',
        help='Formato del reporte (por defecto: both)'
    )
    
    parser.add_argument(
        '--workers', '-w',
        type=int,
        default=4,
        help='Número de workers paralelos (por defecto: 4)'
    )
    
    parser.add_argument(
        '--restore',
        action='store_true',
        help='Restaurar archivos desde el último backup'
    )
    
    args = parser.parse_args()
    
    # Validar directorio
    if not os.path.isdir(args.dir):
        logger.error(f"El directorio no existe: {args.dir}")
        sys.exit(1)
    
    # Cargar configuración
    config = Configuracion(args.config)
    if not config.validar():
        sys.exit(1)
    
    # Inicializar tagger
    hacer_backup = args.backup and not args.no_backup
    tagger = AudioTagger(config, backup=hacer_backup)
    
    # Restaurar backup si se solicita
    if args.restore:
        backup_dir = Path(args.dir)
        backups = sorted(backup_dir.glob('.backup_*'))
        if backups:
            logger.info(f"Restaurando desde: {backups[-1]}")
            # Implementar lógica de restauración
        else:
            logger.warning("No se encontraron backups")
        return
    
    # Procesar archivos
    try:
        tagger.procesar_directorio(args.dir, max_workers=args.workers)
        
        # Generar reportes
        if args.format in ['csv', 'both']:
            tagger.generar_reporte_csv()
        
        if args.format in ['md', 'both']:
            tagger.generar_reporte_md()
        
        logger.info("Proceso completado exitosamente!")
        
    except KeyboardInterrupt:
        logger.info("\nProceso interrumpido por el usuario")
        if tagger.backup_manager:
            logger.info("Los archivos modificados pueden restaurarse desde el backup")
    
    except Exception as e:
        logger.error(f"Error durante el procesamiento: {e}")
        if tagger.backup_manager:
            logger.info("Restaurando archivos desde backup...")
            tagger.backup_manager.restaurar_backup()
        raise


if __name__ == '__main__':
    main()
