#!/usr/bin/env python3
"""
CachaTuMusica - Edición Pro (GUI)
=================================

Aplicación de escritorio moderna para actualización de metadatos musicales.
Usando CustomTkinter para una interfaz elegante y profesional.

Autor: Generated by OpenCode
"""

import os
import sys
import csv
import json
import shutil
import threading
import webbrowser
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, List, Any
from dataclasses import asdict
from concurrent.futures import ThreadPoolExecutor, as_completed
import subprocess

# CustomTkinter - Interfaz moderna
import customtkinter as ctk
from tkinter import filedialog, messagebox

# Procesamiento de audio
import mutagen
from mutagen import File
from mutagen.mp3 import MP3
from mutagen.flac import FLAC
from mutagen.easyid3 import EasyID3
from mutagen.id3 import ID3, TIT2, TPE1, TALB, TDRC, TCON

# Fingerprinting
import acoustid
import musicbrainzngs

# Configuración de tema
ctk.set_appearance_mode("Dark")
ctk.set_default_color_theme("blue")


class CachaTuMusicaGUI:
    """Interfaz gráfica principal de CachaTuMusica"""
    
    def __init__(self):
        self.root = ctk.CTk()
        self.root.title("CachaTuMusica - Edición Pro")
        self.root.geometry("900x750")
        self.root.minsize(850, 700)
        
        # Variables de estado
        self.carpeta_seleccionada = ctk.StringVar(value="")
        self.progreso = ctk.DoubleVar(value=0)
        self.total_archivos = 0
        self.procesados = 0
        self.en_ejecucion = False
        self.dry_run = False
        self.config = self._cargar_config()
        
        # Colores y estilos
        self.colores = {
            "success": "#2ecc71",
            "warning": "#f39c12",
            "error": "#e74c3c",
            "info": "#3498db",
            "bg": "#1a1a1a",
            "fg": "#ffffff"
        }
        
        self._crear_widgets()
        self._mostrar_bienvenida()
    
    def _cargar_config(self) -> Dict:
        """Carga configuración desde archivo"""
        config = {
            'acoustid_api_key': '',
            'openai_api_key': '',
            'ia_enabled': False
        }
        
        # Cargar desde archivo
        if os.path.exists('config.json'):
            try:
                with open('config.json', 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    config['acoustid_api_key'] = data.get('acoustid_api_key', '')
                    config['openai_api_key'] = data.get('openai_api_key', '')
                    config['ia_enabled'] = data.get('ia_enabled', False)
            except:
                pass
        
        # Variables de entorno tienen prioridad
        config['acoustid_api_key'] = os.getenv('ACOUSTID_API_KEY', config['acoustid_api_key'])
        config['openai_api_key'] = os.getenv('OPENAI_API_KEY', config['openai_api_key'])
        
        # Configurar MusicBrainz
        musicbrainzngs.set_useragent(
            "CachaTuMusica",
            "1.0",
            "contact@example.com"
        )
        
        return config
    
    def _crear_widgets(self):
        """Crea todos los widgets de la interfaz"""
        # Frame principal con padding
        self.main_frame = ctk.CTkFrame(self.root, fg_color="transparent")
        self.main_frame.pack(fill="both", expand=True, padx=20, pady=20)
        
        # ========== HEADER ==========
        self.header_frame = ctk.CTkFrame(self.main_frame, fg_color="transparent")
        self.header_frame.pack(fill="x", pady=(0, 20))
        
        # Título
        self.titulo = ctk.CTkLabel(
            self.header_frame,
            text="CachaTuMusica",
            font=ctk.CTkFont(size=32, weight="bold"),
            text_color="#3498db"
        )
        self.titulo.pack()
        
        # Subtítulo
        self.subtitulo = ctk.CTkLabel(
            self.header_frame,
            text="Edición Pro - Actualizador de Metadatos Musicales",
            font=ctk.CTkFont(size=14),
            text_color="gray"
        )
        self.subtitulo.pack()
        
        # Mensaje de bienvenida
        self.welcome_label = ctk.CTkLabel(
            self.header_frame,
            text="El que sabe, sabe. Vamos a dejar tu música impeque.",
            font=ctk.CTkFont(size=12, slant="italic"),
            text_color="#2ecc71"
        )
        self.welcome_label.pack(pady=(5, 0))
        
        # ========== SECCIÓN DE CARPETA ==========
        self.folder_frame = ctk.CTkFrame(self.main_frame)
        self.folder_frame.pack(fill="x", pady=10)
        
        self.folder_label = ctk.CTkLabel(
            self.folder_frame,
            text="📁 Carpeta de Música:",
            font=ctk.CTkFont(size=14, weight="bold")
        )
        self.folder_label.pack(anchor="w", padx=15, pady=(15, 5))
        
        # Frame para entrada y botón
        self.folder_input_frame = ctk.CTkFrame(self.folder_frame, fg_color="transparent")
        self.folder_input_frame.pack(fill="x", padx=15, pady=(0, 15))
        
        self.folder_entry = ctk.CTkEntry(
            self.folder_input_frame,
            textvariable=self.carpeta_seleccionada,
            font=ctk.CTkFont(size=12),
            height=35,
            state="readonly"
        )
        self.folder_entry.pack(side="left", fill="x", expand=True, padx=(0, 10))
        
        self.browse_btn = ctk.CTkButton(
            self.folder_input_frame,
            text="Explorar...",
            font=ctk.CTkFont(size=12),
            height=35,
            width=120,
            command=self._seleccionar_carpeta
        )
        self.browse_btn.pack(side="right")
        
        # ========== OPCIONES ==========
        self.options_frame = ctk.CTkFrame(self.main_frame)
        self.options_frame.pack(fill="x", pady=10)
        
        self.options_label = ctk.CTkLabel(
            self.options_frame,
            text="⚙️ Opciones:",
            font=ctk.CTkFont(size=14, weight="bold")
        )
        self.options_label.pack(anchor="w", padx=15, pady=(15, 5))
        
        # Checkbox para modo simulación
        self.dry_run_var = ctk.BooleanVar(value=False)
        self.dry_run_check = ctk.CTkCheckBox(
            self.options_frame,
            text="Modo Simulación (Dry Run) - No modificar archivos, solo generar reporte",
            variable=self.dry_run_var,
            font=ctk.CTkFont(size=12)
        )
        self.dry_run_check.pack(anchor="w", padx=15, pady=5)
        
        # Checkbox para backup
        self.backup_var = ctk.BooleanVar(value=True)
        self.backup_check = ctk.CTkCheckBox(
            self.options_frame,
            text="Crear backup antes de modificar",
            variable=self.backup_var,
            font=ctk.CTkFont(size=12)
        )
        self.backup_check.pack(anchor="w", padx=15, pady=5)
        
        # Workers
        self.workers_frame = ctk.CTkFrame(self.options_frame, fg_color="transparent")
        self.workers_frame.pack(anchor="w", padx=15, pady=5)
        
        self.workers_label = ctk.CTkLabel(
            self.workers_frame,
            text="Workers paralelos:",
            font=ctk.CTkFont(size=12)
        )
        self.workers_label.pack(side="left", padx=(0, 10))
        
        self.workers_var = ctk.StringVar(value="4")
        self.workers_combo = ctk.CTkComboBox(
            self.workers_frame,
            values=["1", "2", "4", "6", "8"],
            variable=self.workers_var,
            width=80
        )
        self.workers_combo.pack(side="left")
        
        # ========== BARRA DE PROGRESO ==========
        self.progress_frame = ctk.CTkFrame(self.main_frame)
        self.progress_frame.pack(fill="x", pady=10)
        
        self.progress_label = ctk.CTkLabel(
            self.progress_frame,
            text="📊 Progreso:",
            font=ctk.CTkFont(size=14, weight="bold")
        )
        self.progress_label.pack(anchor="w", padx=15, pady=(15, 5))
        
        self.progress_bar = ctk.CTkProgressBar(
            self.progress_frame,
            height=25,
            corner_radius=10
        )
        self.progress_bar.pack(fill="x", padx=15, pady=5)
        self.progress_bar.set(0)
        
        self.progress_text = ctk.CTkLabel(
            self.progress_frame,
            text="0% (0/0 archivos)",
            font=ctk.CTkFont(size=12)
        )
        self.progress_text.pack(anchor="w", padx=15, pady=(0, 10))
        
        # ========== BOTONES DE CONTROL ==========
        self.buttons_frame = ctk.CTkFrame(self.main_frame, fg_color="#1e3a5f", height=70, corner_radius=10)
        self.buttons_frame.pack(fill="x", pady=(10, 5), side="bottom")
        self.buttons_frame.pack_propagate(False)
        
        self.start_btn = ctk.CTkButton(
            self.buttons_frame,
            text="▶️ Iniciar Proceso",
            font=ctk.CTkFont(size=14, weight="bold"),
            height=45,
            fg_color="#2ecc71",
            hover_color="#27ae60",
            command=self._iniciar_proceso
        )
        self.start_btn.pack(side="left", expand=True, fill="both", padx=(0, 5))
        
        self.open_report_btn = ctk.CTkButton(
            self.buttons_frame,
            text="📄 Abrir Reporte",
            font=ctk.CTkFont(size=14),
            height=45,
            fg_color="#3498db",
            hover_color="#2980b9",
            state="disabled",
            command=self._abrir_reporte
        )
        self.open_report_btn.pack(side="right", expand=True, fill="both", padx=(5, 0))
        
        # ========== LOG ==========
        self.log_frame = ctk.CTkFrame(self.main_frame)
        self.log_frame.pack(fill="both", expand=True, pady=10)
        
        self.log_label = ctk.CTkLabel(
            self.log_frame,
            text="📝 Log de Actividad:",
            font=ctk.CTkFont(size=14, weight="bold")
        )
        self.log_label.pack(anchor="w", padx=15, pady=(15, 5))
        
        # Text widget para el log con altura fija
        self.log_text = ctk.CTkTextbox(
            self.log_frame,
            font=ctk.CTkFont(family="Consolas", size=11),
            wrap="word",
            corner_radius=10,
            height=200
        )
        self.log_text.pack(fill="both", expand=True, padx=15, pady=(0, 15))
        
        # Status bar
        self.status_bar = ctk.CTkLabel(
            self.root,
            text="Listo para comenzar",
            font=ctk.CTkFont(size=11),
            fg_color="#2c3e50",
            corner_radius=0,
            height=25
        )
        self.status_bar.pack(fill="x", side="bottom")
    
    def _mostrar_bienvenida(self):
        """Muestra mensaje de bienvenida en el log"""
        self._log("=" * 60, "info")
        self._log("🎵 Bienvenido a CachaTuMusica - Edición Pro", "info")
        self._log("=" * 60, "info")
        self._log("", "info")
        self._log("✨ Funcionalidades:", "info")
        self._log("   • Identificación por huella digital (AcoustID)", "info")
        self._log("   • Fallback con IA para archivos desconocidos", "info")
        self._log("   • Actualización de metadatos ID3v1 e ID3v2", "info")
        self._log("   • Generación de reportes detallados", "info")
        self._log("", "info")
        self._log("👉 Selecciona una carpeta y presiona 'Iniciar Proceso'", "warning")
        self._log("", "info")
    
    def _seleccionar_carpeta(self):
        """Abre diálogo para seleccionar carpeta"""
        carpeta = filedialog.askdirectory(title="Seleccionar carpeta de música")
        if carpeta:
            self.carpeta_seleccionada.set(carpeta)
            self._log(f"📁 Carpeta seleccionada: {carpeta}", "info")
            
            # Contar archivos
            self._contar_archivos(carpeta)
    
    def _contar_archivos(self, carpeta: str):
        """Cuenta archivos de audio en la carpeta"""
        formatos = {'.mp3', '.flac', '.wav', '.m4a', '.ogg', '.wma'}
        count = 0
        
        try:
            for root, dirs, files in os.walk(carpeta):
                for file in files:
                    if Path(file).suffix.lower() in formatos:
                        count += 1
            
            self._log(f"📊 Se encontraron {count} archivos de audio", "success")
            self.total_archivos = count
        except Exception as e:
            self._log(f"⚠️ Error contando archivos: {e}", "error")
    
    def _log(self, mensaje: str, tipo: str = "info"):
        """Agrega mensaje al log con color"""
        colores = {
            "success": "#2ecc71",
            "warning": "#f39c12",
            "error": "#e74c3c",
            "info": "#ffffff"
        }
        
        timestamp = datetime.now().strftime("%H:%M:%S")
        linea = f"[{timestamp}] {mensaje}\n"
        
        self.log_text.configure(state="normal")
        self.log_text.insert("end", linea)
        self.log_text.configure(state="disabled")
        self.log_text.see("end")
    
    def _actualizar_progreso(self, actual: int, total: int):
        """Actualiza la barra de progreso"""
        if total > 0:
            porcentaje = actual / total
            self.progress_bar.set(porcentaje)
            self.progress_text.configure(
                text=f"{int(porcentaje * 100)}% ({actual}/{total} archivos)"
            )
    
    def _iniciar_proceso(self):
        """Inicia el procesamiento en un hilo separado"""
        carpeta = self.carpeta_seleccionada.get()
        
        if not carpeta:
            messagebox.showwarning("Carpeta requerida", "Por favor selecciona una carpeta primero.")
            return
        
        if not os.path.isdir(carpeta):
            messagebox.showerror("Error", "La carpeta seleccionada no existe.")
            return
        
        if not self.config.get('acoustid_api_key'):
            messagebox.showerror("API Key requerida", 
                "ACOUSTID_API_KEY no configurada.\n\n"
                "Configúrala en config.json o en la variable de entorno.")
            return
        
        # Deshabilitar controles durante ejecución
        self._toggle_controles(False)
        self.dry_run = self.dry_run_var.get()
        self.en_ejecucion = True
        self.open_report_btn.configure(state="disabled")
        
        # Limpiar log
        self.log_text.configure(state="normal")
        self.log_text.delete("1.0", "end")
        self.log_text.configure(state="disabled")
        
        if self.dry_run:
            self._log("🔍 MODO SIMULACIÓN ACTIVADO - No se modificarán archivos", "warning")
            self._log("", "info")
        
        self._log("🚀 Iniciando proceso de etiquetado...", "success")
        self._log(f"📁 Carpeta: {carpeta}", "info")
        self._log("", "info")
        
        # Iniciar en hilo separado
        thread = threading.Thread(target=self._procesar_archivos, args=(carpeta,))
        thread.daemon = True
        thread.start()
    
    def _toggle_controles(self, habilitar: bool):
        """Habilita/deshabilita controles durante ejecución"""
        estado = "normal" if habilitar else "disabled"
        self.browse_btn.configure(state=estado)
        self.start_btn.configure(state=estado)
        self.dry_run_check.configure(state=estado)
        self.backup_check.configure(state=estado)
        self.workers_combo.configure(state=estado)
    
    def _procesar_archivos(self, carpeta: str):
        """Procesa los archivos de audio"""
        try:
            formatos = {'.mp3', '.flac', '.wav', '.m4a', '.ogg', '.wma'}
            archivos = []
            
            # Buscar archivos
            for root, dirs, files in os.walk(carpeta):
                for file in files:
                    if Path(file).suffix.lower() in formatos:
                        archivos.append(Path(root) / file)
            
            if not archivos:
                self.root.after(0, lambda: self._log("⚠️ No se encontraron archivos de audio", "warning"))
                return
            
            total = len(archivos)
            self.total_archivos = total
            self.procesados = 0
            resultados = []
            
            workers = int(self.workers_var.get())
            self.root.after(0, lambda: self._log(f"🔄 Procesando {total} archivos con {workers} workers...\n", "info"))
            
            # Procesar con ThreadPool
            with ThreadPoolExecutor(max_workers=workers) as executor:
                futures = {executor.submit(self._procesar_un_archivo, archivo): archivo for archivo in archivos}
                
                for future in as_completed(futures):
                    archivo = futures[future]
                    try:
                        resultado = future.result()
                        self.procesados += 1
                        
                        # Actualizar UI
                        self.root.after(0, lambda a=archivo, r=resultado: self._mostrar_resultado(a, r))
                        self.root.after(0, lambda: self._actualizar_progreso(self.procesados, total))
                        
                        resultados.append({
                            'archivo': str(archivo),
                            'resultado': resultado
                        })
                        
                    except Exception as e:
                        self.root.after(0, lambda a=archivo, e=e: self._log(f"❌ Error en {a.name}: {e}", "error"))
            
            # Generar reporte
            reporte_path = self._generar_reporte(resultados)
            
            self.root.after(0, lambda: self._proceso_completado(reporte_path))
            
        except Exception as e:
            self.root.after(0, lambda e=e: self._log(f"❌ Error general: {e}", "error"))
        finally:
            self.root.after(0, lambda: self._toggle_controles(True))
            self.en_ejecucion = False
    
    def _procesar_un_archivo(self, archivo: Path) -> Dict:
        """Procesa un único archivo"""
        resultado = {
            'status': 'error',
            'fuente': 'N/A',
            'datos': {}
        }
        
        try:
            # Leer tags actuales
            tags_actuales = self._leer_tags(archivo)
            resultado['tags_previos'] = tags_actuales
            
            # Nivel 1: Fingerprinting
            datos = self._identificar_fingerprint(archivo)
            
            if datos:
                resultado['status'] = 'actualizado'
                resultado['fuente'] = 'AcoustID/MusicBrainz'
                resultado['datos'] = datos
            else:
                # Nivel 2: IA Fallback
                if self.config.get('ia_enabled') and self.config.get('openai_api_key'):
                    datos_ia = self._inferir_ia(archivo.name, tags_actuales)
                    if datos_ia:
                        resultado['status'] = 'actualizado'
                        resultado['fuente'] = 'IA'
                        resultado['datos'] = datos_ia
                    else:
                        resultado['status'] = 'no_encontrado'
                else:
                    resultado['status'] = 'no_encontrado'
            
            # Escribir tags si no es dry run
            if resultado['status'] == 'actualizado' and not self.dry_run:
                nuevos_tags = {
                    'title': resultado['datos'].get('title', tags_actuales.get('title')),
                    'artist': resultado['datos'].get('artist', tags_actuales.get('artist')),
                    'album': resultado['datos'].get('album', tags_actuales.get('album')),
                    'year': resultado['datos'].get('year', tags_actuales.get('year')),
                    'genre': resultado['datos'].get('genre', tags_actuales.get('genre'))
                }
                self._escribir_tags(archivo, nuevos_tags)
            
        except Exception as e:
            resultado['status'] = 'error'
            resultado['error'] = str(e)
        
        return resultado
    
    def _leer_tags(self, archivo: Path) -> Dict:
        """Lee tags de un archivo"""
        try:
            audio = File(archivo)
            if audio is None:
                return {}
            
            if isinstance(audio, MP3):
                try:
                    easy = EasyID3(archivo)
                    return {
                        'title': easy.get('title', [''])[0],
                        'artist': easy.get('artist', [''])[0],
                        'album': easy.get('album', [''])[0],
                        'year': easy.get('date', [''])[0],
                        'genre': easy.get('genre', [''])[0]
                    }
                except:
                    pass
            
            return {
                'title': str(audio.get('TIT2', '')),
                'artist': str(audio.get('TPE1', '')),
                'album': str(audio.get('TALB', '')),
                'year': str(audio.get('TDRC', '')),
                'genre': str(audio.get('TCON', ''))
            }
        except:
            return {}
    
    def _identificar_fingerprint(self, archivo: Path) -> Optional[Dict]:
        """Identifica usando fingerprinting"""
        try:
            duracion, fingerprint = acoustid.fingerprint_file(str(archivo))
            resultados = acoustid.lookup(
                self.config['acoustid_api_key'],
                fingerprint,
                duracion,
                meta='recordings releases tracks'
            )
            
            if resultados['status'] != 'ok':
                return None
            
            results = resultados.get('results', [])
            if not results:
                return None
            
            mejor = max(results, key=lambda x: x.get('score', 0))
            if mejor.get('score', 0) < 0.7:
                return None
            
            recordings = mejor.get('recordings', [])
            if not recordings:
                return None
            
            rec = recordings[0]
            artist = rec.get('artists', [{}])[0].get('name') if rec.get('artists') else None
            releases = rec.get('releases', [])
            release = releases[0] if releases else {}
            
            return {
                'title': rec.get('title'),
                'artist': artist,
                'album': release.get('title'),
                'year': None,
                'genre': None
            }
            
        except:
            return None
    
    def _inferir_ia(self, nombre_archivo: str, tags_actuales: Dict) -> Optional[Dict]:
        """Infiere metadatos usando IA"""
        try:
            import openai
            openai.api_key = self.config['openai_api_key']
            
            prompt = f"""Analiza este nombre de archivo y extrae metadatos musicales.
Archivo: {nombre_archivo}

Responde SOLO en JSON:
{{"title": "...", "artist": "...", "album": "...", "year": "...", "genre": "...", "confidence": "alta/media/baja"}}"""
            
            response = openai.ChatCompletion.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "Eres un experto en metadatos musicales."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.3,
                max_tokens=200
            )
            
            contenido = response.choices[0].message.content.strip()
            if '```json' in contenido:
                contenido = contenido.split('```json')[1].split('```')[0].strip()
            
            datos = json.loads(contenido)
            
            if datos.get('confidence') in ['alta', 'media']:
                return {
                    'title': datos.get('title'),
                    'artist': datos.get('artist'),
                    'album': datos.get('album'),
                    'year': str(datos.get('year')) if datos.get('year') else None,
                    'genre': datos.get('genre')
                }
            
            return None
            
        except:
            return None
    
    def _escribir_tags(self, archivo: Path, tags: Dict):
        """Escribe tags en el archivo"""
        try:
            audio = File(archivo)
            if audio is None:
                return
            
            if isinstance(audio, MP3):
                if audio.tags is None:
                    audio.add_tags()
                
                id3 = ID3(archivo)
                if tags.get('title'):
                    id3['TIT2'] = TIT2(encoding=3, text=tags['title'])
                if tags.get('artist'):
                    id3['TPE1'] = TPE1(encoding=3, text=tags['artist'])
                if tags.get('album'):
                    id3['TALB'] = TALB(encoding=3, text=tags['album'])
                if tags.get('year'):
                    id3['TDRC'] = TDRC(encoding=3, text=tags['year'])
                if tags.get('genre'):
                    id3['TCON'] = TCON(encoding=3, text=tags['genre'])
                
                id3.save(archivo)
            
            elif isinstance(audio, FLAC):
                if tags.get('title'):
                    audio['TITLE'] = tags['title']
                if tags.get('artist'):
                    audio['ARTIST'] = tags['artist']
                if tags.get('album'):
                    audio['ALBUM'] = tags['album']
                if tags.get('year'):
                    audio['DATE'] = tags['year']
                if tags.get('genre'):
                    audio['GENRE'] = tags['genre']
                audio.save()
                
        except Exception as e:
            raise e
    
    def _mostrar_resultado(self, archivo: Path, resultado: Dict):
        """Muestra el resultado en el log"""
        nombre = archivo.name
        
        if resultado['status'] == 'actualizado':
            icono = "✅"
            fuente = resultado['fuente']
            self._log(f"{icono} Actualizado: {nombre} | {'🤖' if 'IA' in fuente else '🎵'} Vía {fuente}", "success")
        elif resultado['status'] == 'no_encontrado':
            self._log(f"❓ No encontrado: {nombre}", "warning")
        else:
            self._log(f"❌ Error: {nombre} - {resultado.get('error', 'Desconocido')}", "error")
    
    def _generar_reporte(self, resultados: List[Dict]) -> str:
        """Genera reporte CSV"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"reporte_cachatumusica_{timestamp}.csv"
        
        with open(filename, 'w', newline='', encoding='utf-8-sig') as f:
            writer = csv.writer(f)
            writer.writerow([
                'Archivo', 'Estado', 'Fuente', 
                'Título Anterior', 'Artista Anterior', 
                'Título Nuevo', 'Artista Nuevo', 'Álbum', 'Año', 'Género'
            ])
            
            for item in resultados:
                r = item['resultado']
                tags_previos = r.get('tags_previos', {})
                datos = r.get('datos', {})
                
                writer.writerow([
                    item['archivo'],
                    r['status'],
                    r.get('fuente', 'N/A'),
                    tags_previos.get('title', ''),
                    tags_previos.get('artist', ''),
                    datos.get('title', ''),
                    datos.get('artist', ''),
                    datos.get('album', ''),
                    datos.get('year', ''),
                    datos.get('genre', '')
                ])
        
        return os.path.abspath(filename)
    
    def _proceso_completado(self, reporte_path: str):
        """Llamado cuando termina el proceso"""
        self._log("\n" + "=" * 60, "info")
        self._log("✨ ¡Proceso completado!", "success")
        self._log(f"📊 Reporte guardado en: {reporte_path}", "info")
        self._log("=" * 60, "info")
        
        self.status_bar.configure(text="Proceso completado ✓")
        self.open_report_btn.configure(state="normal")
        self.reporte_path = reporte_path
        
        # Preguntar si abrir reporte
        if messagebox.askyesno("Proceso Completado", 
            "¡El proceso ha finalizado!\n\n¿Deseas abrir el reporte ahora?"):
            self._abrir_reporte()
    
    def _abrir_reporte(self):
        """Abre el reporte CSV"""
        try:
            if hasattr(self, 'reporte_path') and os.path.exists(self.reporte_path):
                if sys.platform == 'win32':
                    os.startfile(self.reporte_path)
                elif sys.platform == 'darwin':
                    subprocess.call(['open', self.reporte_path])
                else:
                    subprocess.call(['xdg-open', self.reporte_path])
            else:
                # Buscar reportes recientes
                reportes = sorted(Path('.').glob('reporte_cachatumusica_*.csv'))
                if reportes:
                    reporte = reportes[-1]
                    if sys.platform == 'win32':
                        os.startfile(str(reporte))
                    elif sys.platform == 'darwin':
                        subprocess.call(['open', str(reporte)])
                    else:
                        subprocess.call(['xdg-open', str(reporte)])
                else:
                    messagebox.showwarning("No encontrado", "No se encontró ningún reporte.")
        except Exception as e:
            messagebox.showerror("Error", f"No se pudo abrir el reporte: {e}")
    
    def run(self):
        """Inicia la aplicación"""
        self.root.mainloop()


def main():
    """Punto de entrada principal"""
    app = CachaTuMusicaGUI()
    app.run()


if __name__ == '__main__':
    main()
